name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore Application/BlazorApp2/BlazorApp2.csproj

      - name: Build the Blazor WASM app
        run: dotnet publish Application/BlazorApp2/BlazorApp2.csproj --configuration Release --output ./publish
      
      - name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
        run: sed -i 's/<base href="\/" \/>/<base href="\/ Epi-Stg-Hub\/Equipment\/" \/>/g' release/wwwroot/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./publish/wwwroot
          destination_dir: ""
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
