name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - deploy  # Trigger deployment when changes are pushed to the 'deploy' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'  # Set up the .NET version

      - name: Restore dependencies
        run: dotnet restore Application/BlazorApp2/BlazorApp2.csproj  # Restore NuGet packages

      - name: Build the Blazor WASM app
        run: dotnet publish Application/BlazorApp2/BlazorApp2.csproj --configuration Release --output ./publish  # Build the app for production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./publish/wwwroot  # Ensure this path is correct for Blazor WASM output
          destination_dir: ""  # Deploy to the root of the gh-pages branch
          publish_branch: gh-pages  # Deploy to the gh-pages branch
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
