name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - gh_pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore Application/BlazorApp2/BlazorApp2.csproj

      - name: Build the Blazor WASM app
        run: dotnet publish Application/BlazorApp2/BlazorApp2.csproj --configuration Release --output ./publish

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./publish/wwwroot
          publish_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

